model dsmodelIterationSelect
  extends Multizone_Commercial_Hydronic.Testcase;
  annotation(__Dymola_SimulationIterationVariables={"heaSys.tABS_detailed.cca2[7].port_a.m_flow",
   "heaSys.tABS_detailed.cca2[6].port_a.m_flow", "heaSys.tABS_detailed.cca2[5].port_a.m_flow",
   "heaSys.tABS_detailed.cca2[4].port_a.m_flow", "heaSys.tABS_detailed.cca2[3].port_a.m_flow",
   "heaSys.tABS_detailed.cca2[2].port_a.m_flow", "heaSys.tABS_detailed.cca3[4].port_a.m_flow",
   "heaSys.tABS_detailed.cca3[3].port_a.m_flow", "heaSys.tABS_detailed.cca3[2].port_a.m_flow",
   "heaSys.tABS_detailed.cca0[9].port_a.m_flow", "heaSys.tABS_detailed.cca0[8].port_a.m_flow",
   "heaSys.tABS_detailed.cca0[7].port_a.m_flow", "heaSys.tABS_detailed.cca0[6].port_a.m_flow",
   "heaSys.tABS_detailed.cca0[5].port_a.m_flow", "heaSys.tABS_detailed.cca0[4].port_a.m_flow",
   "heaSys.tABS_detailed.cca0[3].port_a.m_flow", "heaSys.tABS_detailed.cca0[2].port_a.m_flow",
   "heaSys.tABS_detailed.cca0[1].port_a.m_flow", "heaSys.tABS_detailed.cca0[15].port_a.m_flow",
   "heaSys.tABS_detailed.cca0[14].port_a.m_flow", "heaSys.tABS_detailed.cca0[13].port_a.m_flow",
   "heaSys.tABS_detailed.cca0[12].port_a.m_flow", "heaSys.tABS_detailed.cca0[11].port_a.m_flow",
   "heaSys.tABS_detailed.jun0.port_3.m_flow", "heaSys.tABS_detailed.TWVTABS.res1.dp",
   "heaSys.tABS_detailed.TWVTABS.res3.dp", "heaSys.tABS_detailed.val_coo_sup.dp",
   "heaSys.tABS_detailed.val_heat_sup.dp", "heaSys.tABS_detailed.jun1.port_3.m_flow",
   "heaSys.tABS_detailed.cca1[9].port_a.m_flow", "heaSys.tABS_detailed.cca1[8].port_a.m_flow",
   "heaSys.tABS_detailed.cca1[7].port_a.m_flow", "heaSys.tABS_detailed.cca1[6].port_a.m_flow",
   "heaSys.tABS_detailed.cca1[5].port_a.m_flow", "heaSys.tABS_detailed.cca1[4].port_a.m_flow",
   "heaSys.tABS_detailed.cca1[3].port_a.m_flow", "heaSys.tABS_detailed.cca1[2].port_a.m_flow",
   "heaSys.tABS_detailed.jun2.port_3.m_flow", "heaSys.AHUHeaCoi_a.m_flow", 
  "heaSys.supplyCollector.ports[3].m_flow", "heaSys.AHUCooCoi_b.m_flow", 
  "heaSys.borField.borHol.intHex[1].port_a3.m_flow", "heaSys.pump1.port_a.m_flow",
   "heaSys.e003.port_a2.m_flow", "heaSys.t10.port_a.m_flow", "venSys.dp_HeaCoi_supply[8].dp",
   "venSys.dp_HeaCoi_supply[7].dp", "venSys.dp_HeaCoi_supply[6].dp", 
  "venSys.dp_HeaCoi_supply[5].dp", "venSys.dp_HeaCoi_supply[4].dp", 
  "venSys.dp_HeaCoi_supply[3].dp", "venSys.dp_HeaCoi_supply[2].dp", 
  "venSys.dp_HeaCoi_supply[21].dp", "venSys.dp_HeaCoi_supply[20].dp", 
  "venSys.dp_HeaCoi_supply[1].dp", "venSys.dp_HeaCoi_supply[19].dp", 
  "venSys.dp_HeaCoi_supply[18].dp", "venSys.dp_HeaCoi_supply[17].dp", 
  "venSys.dp_HeaCoi_supply[16].dp", "venSys.dp_HeaCoi_supply[15].dp", 
  "venSys.dp_HeaCoi_supply[14].dp", "venSys.dp_HeaCoi_supply[13].dp", 
  "venSys.dp_HeaCoi_supply[12].dp", "venSys.dp_HeaCoi_supply[11].dp", 
  "venSys.dp_HeaCoi_supply[10].dp", "venSys.dp_HeaCoi_supply[9].dp", 
  "heaSys.supplyCollector.ports[5].m_flow", "heaSys.coolingTower_detailed.cooTow.port_a2.m_flow",
   "heaSys.jun4.port_2.m_flow", "heaSys.t14.port_a.m_flow", "heaSys.heaPum1.con.port_ref.T",
   "heaSys.heaPum1.eva.port_ref.T", "heaSys.heaPum2.con.port_ref.T", 
  "heaSys.heaPum2.eva.port_ref.T", "sim.weaDat.tWetBul_TDryBulXi.TWetBul", 
  "heaSys.pump3.y_actual", "heaSys.tABS_detailed.pump7.y_actual", 
  "buiCon.ctCon.cooTowCon.wetBul.TWetBul", "buiCon.sunSha.sim.weaDat.tWetBul_TDryBulXi.TWetBul",
   "venSys.supplyFan.y_actual", "venSys.exhaustFan.y_actual", "venSys.pump6.y_actual",
   "venSys.pump9.y_actual", "venSys.pump13.y_actual"});
end dsmodelIterationSelect;
